#!/usr/bin/bash
echo "Running Tests"

test_files=$(fd --extension scm --search-path tests)

for test in $test_files; do 
  printf "Test: % s\n" $test 
  guile -s $test 
done
printf "Test Files: %s" test_files
